"""initial

Revision ID: 799cec91299f
Revises: 
Create Date: 2022-09-02 14:38:01.189342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799cec91299f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=68), nullable=False),
    sa.Column('company', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=40), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_applied', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('interview_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('benefits', sa.String(length=100), nullable=False),
    sa.Column('contact_name', sa.String(length=40), nullable=True),
    sa.Column('contact_number', sa.String(length=11), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_date_applied'), ['date_applied'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_interview_date'), ['interview_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_interview_date'))
        batch_op.drop_index(batch_op.f('ix_job_date_applied'))

    op.drop_table('job')
    op.drop_table('user')
    # ### end Alembic commands ###
